### ISSUE TITLE
Running the .jar got me A Java exception has occured error

### ISSUE THREAD

**Issue by anonymousvagrant** [ayunami2000/PotPlayer-LastFM#1]
I am very interested in using your LastFM-Potplayer Scrobbler. Unfortunately, I am unable to run the .jar file as instructed from your Readme.md. I have installed the latest jre-8u421-windows-x64 and run the .jar but was introduced to this error:
![Screenshot 2024-09-14 101536](https://github.com/user-attachments/assets/4dd65f14-51ac-4569-a02e-e165e0b12dc8)

Can you advise how do I run this so that I can have PotPlayer scrobble what videos I am watching. I am using the latest PotPlayer. Does your app require that I log into my LastFM account btw? Do I need to install pre-requisite apps or other tools in order to run your program?

**Comment by ayunami2000** [comment]
Please use a newer Java version. It is working for me on Java 21.0.4 on Windows x64.

**Comment by anonymousvagrant** [comment]
Is this the latest one? So JDK is required? https://www.oracle.com/java/technologies/javase/21-0-4-relnotes.html

**Comment by ayunami2000** [comment]
I personally use binaries from https://adoptium.net

Here is the JRE 21 for Windows x64 .msi from there: https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4%2B7/OpenJDK21U-jre_x64_windows_hotspot_21.0.4_7.msi

**Comment by anonymousvagrant** [comment]
Is there a way to save the settings so that I don't have to login everytime I quit Windows 11?

**Comment by ayunami2000** [comment]
I believe you can pass the setting as a command line argument, but I do not remember for sure. You can thus make a shortcut or batch script to call `java -jar (...).jar (setting)`
